### PR TITLE
documenting base distances

### PR DESCRIPTION
**Pull request by korbelz**
Added human readable values to the base distance code for future devs.

### CODE REVIEW

**Comment by Uganda-streaming** [comment]
Let's goo

**Comment by Uganda-streaming** [comment]
Don't we want to change the sqrDistance to distance function just to make it simpler?

**Comment by korbelz** [comment]
Per the wiki right now DistanceSqr is the "best" way to do it. It could be done either way, if you look at the 2.18 alt syntax you can see DistanceSqr is skipping one step of the math. 

If you can watch this video from khan academy where you live it might explain it better than I can:
https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry/hs-geo-distance-and-midpoints/v/distance-formula

**Comment by Uganda-streaming** [comment]
> Per the wiki right now DistanceSqr is the "best" way to do it. It could be done either way, if you look at the 2.18 alt syntax you can see DistanceSqr is skipping one step of the math.
> 
> If you can watch this video from khan academy where you live it might explain it better than I can: https://www.khanacademy.org/math/geometry/hs-geo-analytic-geometry/hs-geo-distance-and-midpoints/v/distance-formula

But don't we do two more steps to do it by squaring the distance first? :D

**Pull request merged**
