### PR TITLE
Faction Locked Arsenal

### PR DESCRIPTION
**Pull request by ghost**
1. Blacklisted all the Weapons for both the factions
2. Blacklisted all the Launchers for both the factions
3. Handguns are still a gray area but did them anyways
4. Anti Personal Mines & Satchel Charges have been blacklisted
5. All the Files changed accordingly to meet with the requirements
_____________________________________________________________________________________________________________________________________
- [x] Arsenal is Side Locked
- [x] saveSlot Loadouts will be affected by the change 
- [x] loading blacklisted rifles would switch you back to the defaulty rifle based on factions
- [x] loading a blacklisted rifle would switch you back to the PCML for both the factions
- [x] all item would is affected by the blacklisting and loading or owning illegal items would switich you back to the default items

### CODE REVIEW

**Comment by MrThomasM** [comment]
To do:
- [ ] Remove `minesBlaclisted[]` array from both sides in config.cpp
- [ ] Delete `private _minesBlacklist = ["APERSMineDispenser_Mag", "APERSBoundingMine_Range_Mag", "APERSMine_Range_Mag", "APERSTripMine_Wire_Mag", "ClaymoreDirectionalMine_Remote_Mag", "DemoCharge_Remote_Mag", "SatchelCharge_Remote_Mag", "IEDUrbanBig_Remote_Mag", "IEDLandBig_Remote_Mag", "IEDUrbanSmall_Remote_Mag", "IEDLandSmall_Remote_Mag", "TrainingMine_Mag"];` in arsenalSetup.sqf
- [ ] Replace `BIS_fnc_arsenal_data set [23, ((BIS_fnc_arsenal_data select 23) select {!(_x in (getArray (missionConfigFile >> "arsenalConfig" >> _playerSide >> "minesBlaclisted")))})];` with `BIS_fnc_arsenal_data set [23, []];` in arsenalSetup.sqf
- [ ] Remove `handgunsBlacklist[]` from both sides in config.cpp
- [ ] Revert the `sleep 0.1;` to `sleep 0.01;` in orderArsenal.sqf
- [ ] Delete L12-14 in orderArsenal.sqf
- [ ] Delete L23-27 in orderArsenal.sqf
- [ ] Delete L23-39 in orderArsenal.sqf
- [ ] Rewrite code in orderArsenal.sqf, L52-61
- [ ] Rewrite code in orderArsenal.sqf, L75-77

**Comment by MrThomasM** [comment]
keep the pistol whitelist, other then that the reviews are up.

**Comment by notDevChaw** [comment]
Updated per review

**Comment by ghost** [comment]
Fixed and changed the Files to ensure proper restrictions and arsenal cleaning if the blackListed Iteams are loaded
and only loaded

**Pull request closed without merging**
