### PR TITLE
Fixed order in progress bug

### PR DESCRIPTION
**Pull request by korbelz**
'BIS_WL_isOrdering' variable was getting out of sync and stuck to "true". 

BIS_WL_isOrdering check in the order menu was doing nothing other than blocking ordering when it got stuck to true. There was no check in the code anywhere for it to be "true" so made no sense to have it as all. 

I think it was some legacy code that was left over from earlier in dev. It is now removed. 

Dedi server code: ✅
Client side RPT: ✅
Server side RPT: ✅

### CODE REVIEW

**Comment by MrThomasM** [comment]
Alot of sense to keep it, will become very bvious very quickly if you put it on eu11.

**Comment by korbelz** [comment]
The code has zero documentation as to why it was there. Your comment also isn't explaining why the check is there. 

I'm happy to put it back, in fact I keep all the code in the files just for this reason. If there is some reason that only happens on EU#11 that can't be tested anywhere else it needs to be documented and we also need a fix for it.

**Comment by MrThomasM** [comment]
This check was added to stop players from buying new assets before their cp was updated in the database. Removing this check will allow ppl to create lag and then very quickly buy alot of assets.

**Comment by MrThomasM** [comment]
So you could create something diff but a check is needed

**Comment by korbelz** [comment]
Closing this so I can refactor the anti-lag check

**Pull request closed without merging**
