### PR TITLE
Automatic radar

### PR DESCRIPTION
**Pull request by spooker0**
New behavior states:
* When near & looking at static radar defense, a new user action appears for the owner: Turn on Automatic Radar / Shutdown Automatic Radar
* When automatic radar is on: radar rotates 90 degrees every 5 seconds (configurable by server) and radar is set to on. If it sees an enemy air target, it will stop rotating and orient itself on the enemy target (combat mode).
* When automatic radar is off: all behavior is same as normal.
* A player operating the radar, regardless of automatic radar mode, will override the above behaviors.

Testing:
* Confirmed by spawning in enemy jet & helo from 6 km away that a data-linked Centurion can lock on with a static automatic radar on.
* Confirmed with both Bluefor/Opfor radars.
* Confirmed that radar does turn off when automatic radar is shutdown.
* Confirmed that the radar does not automatically rotate / turn on / fight the player even when auto radar is enabled when they are in control.

https://github.com/Gamer-Dad/warlordsredux.altis/assets/5867121/8ec136bc-695b-409a-a6b3-7add8ba0c1ec

### CODE REVIEW

**Comment by spooker0** [comment]
Solo radar + centurion engagement:



https://github.com/Gamer-Dad/warlordsredux.altis/assets/5867121/55831e0c-1313-4bd0-b49c-c5fe602461de

**Comment by MrThomasM** [comment]
Highly doubting that this is good to add, either we keep it on and it turns by itself anyway bc the ai will look around or its off.

**Comment by spooker0** [comment]
> Highly doubting that this is good to add, either we keep it on and it turns by itself anyway bc the ai will look around or its off.

This is from a discord feature request: https://discord.com/channels/819271998362353704/1130260544646033538/1130260544646033538

I can't seem to get the AI to look around on it automatically without forcing the radar to spin. I've tried different combat modes, but that doesn't seem to do anything. They just look in the general direction they're placed in until something comes into their IR view range (?).

Don't think there's a performance impact because it only executes a lookAt once every 5 seconds for every radar. I can profile this if this is a concern.

**Comment by MrThomasM** [comment]
The radar beeing on part is fine but making it turn, and making it turn this way is just not worth it.

**Comment by spooker0** [comment]
> The radar beeing on part is fine but making it turn, and making it turn this way is just not worth it.

Ok, I've removed the turning code. 

Testing it, it will still allow you to solo a radar+SAM, but you have to do the turning manually and find the target with automatic radar on, then switch to your SAM.

**Pull request merged**
